import type {
  Alarm,
  AuditEvent,
  Asset,
  ContractorCompany,
  Location,
  NotificationItem,
  NotificationPreference,
  Organisation,
  PPMTask,
  PortalDocument,
  Property,
  Quotation,
  TelemetryPoint,
  User,
  WorkOrder,
} from "./types";

export const currentOrganisation: Organisation = {
  id: "org_kx-estates",
  name: "King's Cross Estates Ltd",
  billingPlan: "Standard",
};

export const currentUser: User = {
  id: "user_1",
  name: "Amara Osei",
  email: "amara.osei@kx-estates.co.uk",
  role: "CUSTOMER_PORTFOLIO_ADMIN",
  organisationId: currentOrganisation.id,
  initials: "AO",
};

export const properties: Property[] = [
  {
    id: "prop_coal-drops-4",
    organisationId: currentOrganisation.id,
    name: "Coal Drops Yard - Unit 4",
    addressLine1: "Coal Drops Yard, Unit 4",
    town: "London",
    postcode: "N1C 4DQ",
    propertyType: "Retail",
    status: "active",
    openJobs: 2,
    compliancePercent: 98,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "Today",
    responsibleManager: "Amara Osei",
    region: "Central London",
    scan: {
      provider: "Polycam",
      capturedAt: "2026-02-11",
      status: "current",
      coordinateSystem: "Local (scan-relative)",
      sourceFiles: "GLB + point cloud archive",
    },
  },
  {
    id: "prop_camden-retail",
    organisationId: currentOrganisation.id,
    name: "Retail Unit - Camden",
    addressLine1: "14 Chalk Farm Road",
    town: "London",
    postcode: "NW1 8AG",
    propertyType: "Retail",
    status: "active",
    openJobs: 1,
    compliancePercent: 91,
    complianceRisk: "due-soon",
    slaRisk: false,
    documentsDue: 1,
    lastActivity: "Yesterday",
    responsibleManager: "Amara Osei",
    region: "Central London",
  },
  {
    id: "prop_ha9-social",
    organisationId: currentOrganisation.id,
    name: "Social Housing - HA9",
    addressLine1: "Olympic Way Block C",
    town: "Wembley",
    postcode: "HA9 0DB",
    propertyType: "Residential",
    status: "active",
    openJobs: 0,
    compliancePercent: 96,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "3 days ago",
    responsibleManager: "Femi Adeyemi",
    region: "North West London",
  },
  {
    id: "prop_kings-cross-office",
    organisationId: currentOrganisation.id,
    name: "Office - King's Cross",
    addressLine1: "5 Pancras Square",
    town: "London",
    postcode: "N1C 4AG",
    propertyType: "Office",
    status: "active",
    openJobs: 5,
    compliancePercent: 84,
    complianceRisk: "overdue",
    slaRisk: true,
    documentsDue: 3,
    lastActivity: "Today",
    responsibleManager: "Amara Osei",
    region: "Central London",
    scan: {
      provider: "Matterport",
      capturedAt: "2025-10-03",
      status: "current",
      coordinateSystem: "Matterport SDK (converted on import)",
      sourceFiles: "Matterport model + panoramic walkthrough",
    },
  },
  {
    id: "prop_shoreditch-office",
    organisationId: currentOrganisation.id,
    name: "Office - Shoreditch",
    addressLine1: "22 Old Street",
    town: "London",
    postcode: "EC1V 9DD",
    propertyType: "Office",
    status: "active",
    openJobs: 1,
    compliancePercent: 93,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "2 days ago",
    responsibleManager: "Femi Adeyemi",
    region: "Central London",
  },
  {
    id: "prop_croydon-industrial",
    organisationId: currentOrganisation.id,
    name: "Industrial Unit - Croydon",
    addressLine1: "Purley Way Trade Park, Unit 9",
    town: "Croydon",
    postcode: "CR0 4RQ",
    propertyType: "Industrial",
    status: "active",
    openJobs: 0,
    compliancePercent: 100,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "5 days ago",
    responsibleManager: "Femi Adeyemi",
    region: "South London",
  },
  {
    id: "prop_stratford-retail",
    organisationId: currentOrganisation.id,
    name: "Retail Unit - Stratford",
    addressLine1: "Westfield Avenue, Kiosk 3",
    town: "London",
    postcode: "E20 1EJ",
    propertyType: "Retail",
    status: "active",
    openJobs: 1,
    compliancePercent: 88,
    complianceRisk: "due-soon",
    slaRisk: false,
    documentsDue: 1,
    lastActivity: "Yesterday",
    responsibleManager: "Amara Osei",
    region: "East London",
  },
  {
    id: "prop_ealing-mixed",
    organisationId: currentOrganisation.id,
    name: "Mixed Use - Ealing Broadway",
    addressLine1: "The Broadway, Block B",
    town: "London",
    postcode: "W5 5JY",
    propertyType: "Mixed use",
    status: "onboarding",
    openJobs: 0,
    compliancePercent: 0,
    complianceRisk: "due-soon",
    slaRisk: false,
    documentsDue: 2,
    lastActivity: "1 week ago",
    responsibleManager: "Femi Adeyemi",
    region: "West London",
  },
  {
    id: "prop_hackney-residential",
    organisationId: currentOrganisation.id,
    name: "Social Housing - Hackney",
    addressLine1: "Mare Street Estate, Block 2",
    town: "London",
    postcode: "E8 3RH",
    propertyType: "Residential",
    status: "active",
    openJobs: 2,
    compliancePercent: 95,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "Today",
    responsibleManager: "Femi Adeyemi",
    region: "East London",
  },
  {
    id: "prop_greenwich-office",
    organisationId: currentOrganisation.id,
    name: "Office - Greenwich Peninsula",
    addressLine1: "12 Edmund Halley Way",
    town: "London",
    postcode: "SE10 0BQ",
    propertyType: "Office",
    status: "active",
    openJobs: 0,
    compliancePercent: 97,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "4 days ago",
    responsibleManager: "Amara Osei",
    region: "South East London",
  },
  {
    id: "prop_wandsworth-retail",
    organisationId: currentOrganisation.id,
    name: "Retail Unit - Wandsworth",
    addressLine1: "Southside, Unit 21",
    town: "London",
    postcode: "SW18 4TF",
    propertyType: "Retail",
    status: "active",
    openJobs: 1,
    compliancePercent: 89,
    complianceRisk: "due-soon",
    slaRisk: false,
    documentsDue: 1,
    lastActivity: "2 days ago",
    responsibleManager: "Amara Osei",
    region: "South West London",
  },
  {
    id: "prop_barking-industrial",
    organisationId: currentOrganisation.id,
    name: "Industrial Unit - Barking",
    addressLine1: "River Road Business Park, Unit 4",
    town: "Barking",
    postcode: "IG11 0DA",
    propertyType: "Industrial",
    status: "inactive",
    openJobs: 0,
    compliancePercent: 100,
    complianceRisk: "on-track",
    slaRisk: false,
    documentsDue: 0,
    lastActivity: "3 weeks ago",
    responsibleManager: "Femi Adeyemi",
    region: "East London",
  },
];

export const locations: Location[] = [
  { id: "loc_cd4-ground", propertyId: "prop_coal-drops-4", parentId: null, kind: "floor", name: "Ground Floor" },
  { id: "loc_cd4-kitchen", propertyId: "prop_coal-drops-4", parentId: "loc_cd4-ground", kind: "room", name: "Basement Kitchen" },
  { id: "loc_cd4-plant", propertyId: "prop_coal-drops-4", parentId: "loc_cd4-ground", kind: "room", name: "Plant Room" },
  { id: "loc_cd4-shopfloor", propertyId: "prop_coal-drops-4", parentId: "loc_cd4-ground", kind: "zone", name: "Shop Floor" },

  { id: "loc_kx-l1", propertyId: "prop_kings-cross-office", parentId: null, kind: "floor", name: "Level 1" },
  { id: "loc_kx-l3", propertyId: "prop_kings-cross-office", parentId: null, kind: "floor", name: "Level 3" },
  { id: "loc_kx-plant", propertyId: "prop_kings-cross-office", parentId: "loc_kx-l1", kind: "room", name: "Roof Plant Room" },
  { id: "loc_kx-lobby", propertyId: "prop_kings-cross-office", parentId: "loc_kx-l1", kind: "zone", name: "Main Lobby" },
  { id: "loc_kx-l3-east", propertyId: "prop_kings-cross-office", parentId: "loc_kx-l3", kind: "zone", name: "East Core" },

  { id: "loc_camden-ground", propertyId: "prop_camden-retail", parentId: null, kind: "floor", name: "Ground Floor" },
  { id: "loc_camden-store", propertyId: "prop_camden-retail", parentId: "loc_camden-ground", kind: "room", name: "Stockroom" },

  { id: "loc_ha9-blockc", propertyId: "prop_ha9-social", parentId: null, kind: "floor", name: "Block C" },
  { id: "loc_ha9-comms", propertyId: "prop_ha9-social", parentId: "loc_ha9-blockc", kind: "room", name: "Communal Hallway" },
];

export const assets: Asset[] = [
  {
    id: "asset_sk-014",
    propertyId: "prop_coal-drops-4",
    locationId: "loc_cd4-kitchen",
    locationLabel: "Basement Kitchen",
    assetType: "Sink",
    system: "Plumbing",
    tagCode: "SK-014",
    manufacturer: "Franke",
    model: "Sissons",
    serial: "FR-88213",
    installDate: "2021-03-14",
    expectedLifeYears: 15,
    condition: "good",
    criticality: "medium",
    nextServiceDue: "2026-11-02",
    maintenanceContractor: "Metro Plumbing Services",
    status: "faulty",
    anchor: { x: 28, y: 62 },
  },
  {
    id: "asset_ahu-02",
    propertyId: "prop_coal-drops-4",
    locationId: "loc_cd4-plant",
    locationLabel: "Plant Room",
    assetType: "AHU (Air Handling Unit)",
    system: "HVAC",
    tagCode: "AHU-02",
    manufacturer: "Swegon",
    model: "GOLD RX 15",
    serial: "SW-451209",
    installDate: "2019-06-01",
    expectedLifeYears: 20,
    condition: "fair",
    criticality: "high",
    nextServiceDue: "2026-09-18",
    maintenanceContractor: "Climate Care Ltd",
    status: "in-service",
    anchor: { x: 72, y: 30 },
  },
  {
    id: "asset_fd-11",
    propertyId: "prop_coal-drops-4",
    locationId: "loc_cd4-shopfloor",
    locationLabel: "Shop Floor - Rear Exit",
    assetType: "Fire Door",
    system: "Life Safety",
    tagCode: "FD-11",
    installDate: "2021-03-01",
    condition: "good",
    criticality: "life-safety",
    nextServiceDue: "2026-08-05",
    maintenanceContractor: "Sentinel Fire & Security",
    status: "in-service",
    anchor: { x: 50, y: 85 },
  },
  {
    id: "asset_ahu-07",
    propertyId: "prop_kings-cross-office",
    locationId: "loc_kx-plant",
    locationLabel: "Roof Plant Room",
    assetType: "AHU (Air Handling Unit)",
    system: "HVAC",
    tagCode: "AHU-07",
    manufacturer: "Trox",
    model: "X-CUBE Compact",
    serial: "TX-902344",
    installDate: "2018-02-11",
    expectedLifeYears: 20,
    condition: "poor",
    criticality: "high",
    nextServiceDue: "2026-07-25",
    maintenanceContractor: "Climate Care Ltd",
    status: "faulty",
    anchor: { x: 35, y: 20 },
  },
  {
    id: "asset_el-22",
    propertyId: "prop_kings-cross-office",
    locationId: "loc_kx-l3-east",
    locationLabel: "Level 3 - East Core",
    assetType: "Emergency Lighting",
    system: "Electrical",
    tagCode: "EL-22",
    installDate: "2020-09-01",
    condition: "fair",
    criticality: "life-safety",
    nextServiceDue: "2026-08-01",
    maintenanceContractor: "Sentinel Fire & Security",
    status: "faulty",
    anchor: { x: 80, y: 55 },
  },
  {
    id: "asset_lift-01",
    propertyId: "prop_kings-cross-office",
    locationId: "loc_kx-lobby",
    locationLabel: "Main Lobby",
    assetType: "Lift / Elevator",
    system: "Vertical Transport",
    tagCode: "LIFT-01",
    manufacturer: "KONE",
    model: "MonoSpace 500",
    serial: "KN-771221",
    installDate: "2017-11-20",
    expectedLifeYears: 25,
    condition: "good",
    criticality: "high",
    nextServiceDue: "2026-10-14",
    maintenanceContractor: "KONE Service",
    status: "in-service",
    anchor: { x: 50, y: 75 },
  },
  {
    id: "asset_sk-003",
    propertyId: "prop_camden-retail",
    locationId: "loc_camden-store",
    locationLabel: "Stockroom",
    assetType: "Sink",
    system: "Plumbing",
    tagCode: "SK-003",
    installDate: "2020-01-10",
    condition: "fair",
    criticality: "low",
    nextServiceDue: "2026-12-01",
    maintenanceContractor: "Metro Plumbing Services",
    status: "in-service",
    anchor: { x: 60, y: 40 },
  },
  {
    id: "asset_el-05",
    propertyId: "prop_ha9-social",
    locationId: "loc_ha9-comms",
    locationLabel: "Communal Hallway",
    assetType: "Emergency Lighting",
    system: "Electrical",
    tagCode: "EL-05",
    installDate: "2022-05-01",
    condition: "good",
    criticality: "life-safety",
    nextServiceDue: "2026-09-01",
    maintenanceContractor: "Sentinel Fire & Security",
    status: "in-service",
    anchor: { x: 45, y: 50 },
  },
];

export const workOrders: WorkOrder[] = [
  {
    id: "wo_1042",
    reference: "SA-1042",
    organisationId: currentOrganisation.id,
    propertyId: "prop_coal-drops-4",
    propertyName: "Coal Drops Yard - Unit 4",
    locationLabel: "Basement Kitchen",
    assetId: "asset_sk-014",
    assetLabel: "Sink SK-014",
    faultCode: "SINK_NO_HOT_WATER",
    faultLabel: "No hot water",
    description: "Water starts warm then runs cold within a minute.",
    priority: "NORMAL",
    status: "Scheduled",
    slaTargetHours: 48,
    raisedBy: "Amara Osei",
    raisedAt: "2026-07-17T09:12:00+01:00",
    assignedTo: "Metro Plumbing Services",
    scheduledFor: "2026-07-21T09:00:00+01:00",
    trade: "Plumbing",
    events: [
      { id: "ev1", timestamp: "2026-07-17T09:12:00+01:00", actor: "Amara Osei", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-17T10:03:00+01:00", actor: "S&A Helpdesk", description: "Triaged and priority confirmed as Normal." },
      { id: "ev3", timestamp: "2026-07-17T14:20:00+01:00", actor: "S&A Helpdesk", description: "Assigned to Metro Plumbing Services." },
      { id: "ev4", timestamp: "2026-07-18T08:45:00+01:00", actor: "Metro Plumbing Services", description: "Appointment scheduled for 21 Jul, 09:00–13:00." },
    ],
  },
  {
    id: "wo_1043",
    reference: "SA-1043",
    organisationId: currentOrganisation.id,
    propertyId: "prop_coal-drops-4",
    propertyName: "Coal Drops Yard - Unit 4",
    locationLabel: "Plant Room",
    assetId: "asset_ahu-02",
    assetLabel: "AHU AHU-02",
    faultCode: "AHU_UNUSUAL_NOISE",
    faultLabel: "Unusual noise",
    description: "Rattling noise from unit 2 when running on high fan speed.",
    priority: "LOW",
    status: "Triaged",
    slaTargetHours: 120,
    raisedBy: "Amara Osei",
    raisedAt: "2026-07-18T11:30:00+01:00",
    trade: "HVAC",
    events: [
      { id: "ev1", timestamp: "2026-07-18T11:30:00+01:00", actor: "Amara Osei", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-18T13:10:00+01:00", actor: "S&A Helpdesk", description: "Triaged; awaiting contractor allocation." },
    ],
  },
  {
    id: "wo_1044",
    reference: "SA-1044",
    organisationId: currentOrganisation.id,
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    locationLabel: "Roof Plant Room",
    assetId: "asset_ahu-07",
    assetLabel: "AHU AHU-07",
    faultCode: "AHU_NO_COOLING",
    faultLabel: "No cooling",
    description: "Zone temperature climbing on Level 3 East since Friday.",
    priority: "URGENT",
    status: "In progress",
    slaTargetHours: 24,
    raisedBy: "Ravi Chandra",
    raisedAt: "2026-07-18T08:05:00+01:00",
    assignedTo: "Climate Care Ltd",
    scheduledFor: "2026-07-19T10:00:00+01:00",
    trade: "HVAC",
    events: [
      { id: "ev1", timestamp: "2026-07-18T08:05:00+01:00", actor: "Ravi Chandra", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-18T08:40:00+01:00", actor: "S&A Helpdesk", description: "Triaged as Urgent; assigned to Climate Care Ltd." },
      { id: "ev3", timestamp: "2026-07-19T09:58:00+01:00", actor: "Climate Care Ltd", description: "Engineer on site, diagnosing compressor fault." },
    ],
  },
  {
    id: "wo_1045",
    reference: "SA-1045",
    organisationId: currentOrganisation.id,
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    locationLabel: "Level 3 - East Core",
    assetId: "asset_el-22",
    assetLabel: "Emergency Lighting EL-22",
    faultCode: "EL_NOT_ILLUMINATING",
    faultLabel: "Not illuminating",
    description: "Unit failed monthly function test - no illumination on discharge.",
    priority: "URGENT",
    status: "Awaiting parts",
    slaTargetHours: 24,
    raisedBy: "S&A Engineer",
    raisedAt: "2026-07-15T15:00:00+01:00",
    assignedTo: "Sentinel Fire & Security",
    trade: "Electrical",
    events: [
      { id: "ev1", timestamp: "2026-07-15T15:00:00+01:00", actor: "S&A Engineer", description: "Raised from failed PPM test." },
      { id: "ev2", timestamp: "2026-07-16T09:00:00+01:00", actor: "Sentinel Fire & Security", description: "Attended; replacement battery required." },
      { id: "ev3", timestamp: "2026-07-16T09:05:00+01:00", actor: "Sentinel Fire & Security", description: "Part ordered, ETA 3 working days." },
    ],
  },
  {
    id: "wo_1046",
    reference: "SA-1046",
    organisationId: currentOrganisation.id,
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    locationLabel: "Main Lobby",
    assetId: "asset_lift-01",
    assetLabel: "Lift LIFT-01",
    faultCode: "LIFT_UNUSUAL_NOISE",
    faultLabel: "Unusual noise / vibration",
    description: "Slight vibration felt between floors 2 and 3.",
    priority: "NORMAL",
    status: "New",
    slaTargetHours: 48,
    raisedBy: "Ravi Chandra",
    raisedAt: "2026-07-19T08:20:00+01:00",
    trade: "Lifts",
    events: [
      { id: "ev1", timestamp: "2026-07-19T08:20:00+01:00", actor: "Ravi Chandra", description: "Job submitted via portal." },
    ],
  },
  {
    id: "wo_1047",
    reference: "SA-1047",
    organisationId: currentOrganisation.id,
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    locationLabel: "Level 1",
    assetId: null,
    assetLabel: null,
    faultCode: "GENERAL_OTHER",
    faultLabel: "General facilities request",
    description: "Meeting room 1.4 blinds jammed half open.",
    priority: "LOW",
    status: "Customer review",
    slaTargetHours: 120,
    raisedBy: "Ravi Chandra",
    raisedAt: "2026-07-10T10:00:00+01:00",
    assignedTo: "S&A Engineer",
    trade: "General fabric",
    events: [
      { id: "ev1", timestamp: "2026-07-10T10:00:00+01:00", actor: "Ravi Chandra", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-11T09:00:00+01:00", actor: "S&A Engineer", description: "Attended and repaired blind mechanism." },
      { id: "ev3", timestamp: "2026-07-11T09:20:00+01:00", actor: "S&A Engineer", description: "Marked completed; awaiting customer confirmation." },
    ],
  },
  {
    id: "wo_1048",
    reference: "SA-1048",
    organisationId: currentOrganisation.id,
    propertyId: "prop_camden-retail",
    propertyName: "Retail Unit - Camden",
    locationLabel: "Stockroom",
    assetId: "asset_sk-003",
    assetLabel: "Sink SK-003",
    faultCode: "SINK_BLOCKAGE",
    faultLabel: "Blockage",
    description: "Slow-draining sink, occasional backup.",
    priority: "NORMAL",
    status: "Assigned",
    slaTargetHours: 48,
    raisedBy: "Store Manager",
    raisedAt: "2026-07-18T16:40:00+01:00",
    assignedTo: "Metro Plumbing Services",
    trade: "Plumbing",
    events: [
      { id: "ev1", timestamp: "2026-07-18T16:40:00+01:00", actor: "Store Manager", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-19T08:10:00+01:00", actor: "S&A Helpdesk", description: "Assigned to Metro Plumbing Services." },
    ],
  },
  {
    id: "wo_1039",
    reference: "SA-1039",
    organisationId: currentOrganisation.id,
    propertyId: "prop_hackney-residential",
    propertyName: "Social Housing - Hackney",
    locationLabel: "Communal Hallway",
    assetId: null,
    assetLabel: null,
    faultCode: "GENERAL_OTHER",
    faultLabel: "Communal door entry fault",
    description: "Entry phone at Block 2 not buzzing through to flats 12-18.",
    priority: "URGENT",
    status: "Closed",
    slaTargetHours: 24,
    raisedBy: "Femi Adeyemi",
    raisedAt: "2026-07-05T09:00:00+01:00",
    assignedTo: "S&A Engineer",
    trade: "Electrical",
    events: [
      { id: "ev1", timestamp: "2026-07-05T09:00:00+01:00", actor: "Femi Adeyemi", description: "Job submitted via portal." },
      { id: "ev2", timestamp: "2026-07-05T13:00:00+01:00", actor: "S&A Engineer", description: "Attended, replaced entry panel module." },
      { id: "ev3", timestamp: "2026-07-05T13:30:00+01:00", actor: "S&A Engineer", description: "Completed and evidence uploaded." },
      { id: "ev4", timestamp: "2026-07-07T10:00:00+01:00", actor: "Femi Adeyemi", description: "Confirmed resolved and closed." },
    ],
  },
];

export const documents: PortalDocument[] = [
  { id: "doc_1", propertyId: "prop_coal-drops-4", title: "Coal Drops Yard Unit 4 - Mechanical & Electrical As-Built", category: "Drawing", version: "3.1", revisionDate: "2024-11-02", author: "BuildTech Consulting", visibility: "customer", status: "current", fileType: "DWG" },
  { id: "doc_2", propertyId: "prop_coal-drops-4", title: "Fire Risk Assessment", category: "Report", version: "2.0", revisionDate: "2025-09-14", reviewDate: "2026-09-14", author: "Sentinel Fire & Security", visibility: "customer", status: "current", fileType: "PDF" },
  { id: "doc_3", propertyId: "prop_coal-drops-4", title: "Gas Safety Certificate - Kitchen", category: "Certificate", version: "1.0", revisionDate: "2025-12-01", reviewDate: "2026-12-01", author: "Metro Plumbing Services", visibility: "customer", status: "current", fileType: "PDF" },
  { id: "doc_4", propertyId: "prop_coal-drops-4", title: "Water Isolation Record - Basement Kitchen", category: "Isolation record", version: "1.2", revisionDate: "2026-03-11", reviewDate: "2026-09-11", author: "S&A Engineering", visibility: "internal", status: "current", fileType: "PDF" },
  { id: "doc_5", propertyId: "prop_kings-cross-office", title: "5 Pancras Square - Base Build Drawings", category: "Drawing", version: "5.0", revisionDate: "2023-06-20", author: "Pancras Design Partnership", visibility: "customer", status: "superseded", fileType: "DWG" },
  { id: "doc_6", propertyId: "prop_kings-cross-office", title: "Lift LOLER Inspection Report", category: "Report", version: "1.0", revisionDate: "2026-04-14", reviewDate: "2026-10-14", author: "KONE Service", visibility: "customer", status: "current", fileType: "PDF" },
  { id: "doc_7", propertyId: "prop_kings-cross-office", title: "Emergency Lighting Test Log", category: "Report", version: "1.0", revisionDate: "2026-07-15", author: "Sentinel Fire & Security", visibility: "customer", status: "current", fileType: "XLSX" },
  { id: "doc_8", propertyId: "prop_kings-cross-office", title: "Electrical Isolation Schedule - Roof Plant", category: "Isolation record", version: "2.1", revisionDate: "2025-01-09", reviewDate: "2026-01-09", author: "S&A Engineering", visibility: "internal", status: "unverified", fileType: "PDF" },
  { id: "doc_9", propertyId: "prop_camden-retail", title: "EICR - Retail Unit", category: "Certificate", version: "1.0", revisionDate: "2025-08-01", reviewDate: "2030-08-01", author: "Approved Electrical Contractors", visibility: "customer", status: "current", fileType: "PDF" },
  { id: "doc_10", propertyId: "prop_ha9-social", title: "Legionella Risk Assessment", category: "Report", version: "1.0", revisionDate: "2025-05-19", reviewDate: "2027-05-19", author: "Water Hygiene Solutions", visibility: "customer", status: "current", fileType: "PDF" },
];

export const ppmTasks: PPMTask[] = [
  { id: "ppm_1", propertyId: "prop_kings-cross-office", assetId: "asset_el-22", assetLabel: "Emergency Lighting EL-22", taskName: "Monthly function test", frequency: "Monthly", contractor: "Sentinel Fire & Security", dueDate: "2026-07-31", status: "exception", category: "Fire" },
  { id: "ppm_2", propertyId: "prop_kings-cross-office", assetId: "asset_lift-01", assetLabel: "Lift LIFT-01", taskName: "LOLER thorough examination", frequency: "Six-monthly", contractor: "KONE Service", dueDate: "2026-10-14", status: "scheduled", category: "General" },
  { id: "ppm_3", propertyId: "prop_kings-cross-office", assetId: "asset_ahu-07", assetLabel: "AHU AHU-07", taskName: "Quarterly filter change and service", frequency: "Quarterly", contractor: "Climate Care Ltd", dueDate: "2026-07-25", status: "due-soon", category: "HVAC" },
  { id: "ppm_4", propertyId: "prop_coal-drops-4", assetId: "asset_fd-11", assetLabel: "Fire Door FD-11", taskName: "Fire door inspection", frequency: "Six-monthly", contractor: "Sentinel Fire & Security", dueDate: "2026-08-05", status: "scheduled", category: "Fire" },
  { id: "ppm_5", propertyId: "prop_coal-drops-4", assetId: "asset_ahu-02", assetLabel: "AHU AHU-02", taskName: "AHU annual service", frequency: "Annual", contractor: "Climate Care Ltd", dueDate: "2026-09-18", status: "scheduled", category: "HVAC" },
  { id: "ppm_6", propertyId: "prop_ha9-social", assetId: "asset_el-05", assetLabel: "Emergency Lighting EL-05", taskName: "Monthly function test", frequency: "Monthly", contractor: "Sentinel Fire & Security", dueDate: "2026-07-30", status: "scheduled", category: "Fire" },
  { id: "ppm_7", propertyId: "prop_camden-retail", assetId: "asset_sk-003", assetLabel: "Sink SK-003", taskName: "Water hygiene TMV service", frequency: "Annual", contractor: "Water Hygiene Solutions", dueDate: "2026-07-22", status: "overdue", category: "Water hygiene" },
  { id: "ppm_8", propertyId: "prop_kings-cross-office", assetId: "asset_lift-01", assetLabel: "Lift LIFT-01", taskName: "Weekly visual safety check", frequency: "Weekly", contractor: "S&A Engineering", dueDate: "2026-07-20", status: "due-soon", category: "General" },
];

export const auditEvents: AuditEvent[] = [
  { id: "audit_1", timestamp: "2026-07-19T08:20:00+01:00", actor: "Ravi Chandra", action: "created", entity: "Work order SA-1046" },
  { id: "audit_2", timestamp: "2026-07-18T13:10:00+01:00", actor: "S&A Helpdesk", action: "updated status", entity: "Work order SA-1043", oldValue: "New", newValue: "Triaged" },
  { id: "audit_3", timestamp: "2026-07-16T09:05:00+01:00", actor: "Sentinel Fire & Security", action: "updated status", entity: "Work order SA-1045", oldValue: "Scheduled", newValue: "Awaiting parts" },
  { id: "audit_4", timestamp: "2026-07-11T09:20:00+01:00", actor: "S&A Engineer", action: "uploaded evidence", entity: "Work order SA-1047" },
  { id: "audit_5", timestamp: "2026-07-05T13:30:00+01:00", actor: "S&A Engineer", action: "closed", entity: "Work order SA-1039" },
  { id: "audit_6", timestamp: "2026-03-11T11:00:00+01:00", actor: "S&A Engineering", action: "verified", entity: "Water Isolation Record - Basement Kitchen" },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getAssetsForProperty(propertyId: string): Asset[] {
  return assets.filter((a) => a.propertyId === propertyId);
}

export function getLocationsForProperty(propertyId: string): Location[] {
  return locations.filter((l) => l.propertyId === propertyId);
}

export function getWorkOrdersForProperty(propertyId: string): WorkOrder[] {
  return workOrders.filter((w) => w.propertyId === propertyId);
}

export function getDocumentsForProperty(propertyId: string): PortalDocument[] {
  return documents.filter((d) => d.propertyId === propertyId);
}

export function getPPMTasksForProperty(propertyId: string): PPMTask[] {
  return ppmTasks.filter((t) => t.propertyId === propertyId);
}

export function getWorkOrderById(id: string): WorkOrder | undefined {
  return workOrders.find((w) => w.id === id);
}

export function getAssetById(id: string): Asset | undefined {
  return assets.find((a) => a.id === id);
}

// Section 10 — BMS and IoT integration (read-only).

function synthReadings(base: number, amplitude: number, points = 12): { t: string; v: number }[] {
  return Array.from({ length: points }, (_, i) => {
    const hoursAgo = (points - 1 - i) * 2;
    const wave = Math.sin(i / 2) * amplitude;
    return {
      t: new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString(),
      v: Math.round((base + wave) * 10) / 10,
    };
  });
}

export const telemetryPoints: TelemetryPoint[] = [
  {
    id: "tp_ahu07_supply",
    assetId: "asset_ahu-07",
    propertyId: "prop_kings-cross-office",
    label: "Supply air temperature",
    unit: "°C",
    source: "BACnet/IP",
    lastUpdated: "2026-07-19T09:40:00+01:00",
    freshness: "live",
    readings: synthReadings(19, 4),
  },
  {
    id: "tp_ahu07_power",
    assetId: "asset_ahu-07",
    propertyId: "prop_kings-cross-office",
    label: "Compressor power draw",
    unit: "kW",
    source: "BACnet/IP",
    lastUpdated: "2026-07-19T09:40:00+01:00",
    freshness: "live",
    readings: synthReadings(7.5, 1.8),
  },
  {
    id: "tp_ahu02_supply",
    assetId: "asset_ahu-02",
    propertyId: "prop_coal-drops-4",
    label: "Supply air temperature",
    unit: "°C",
    source: "MQTT",
    lastUpdated: "2026-07-19T09:15:00+01:00",
    freshness: "delayed",
    readings: synthReadings(21, 1.5),
  },
  {
    id: "tp_lift01_trips",
    assetId: "asset_lift-01",
    propertyId: "prop_kings-cross-office",
    label: "Daily trip count",
    unit: "trips",
    source: "Vendor API",
    lastUpdated: "2026-07-19T06:00:00+01:00",
    freshness: "live",
    readings: synthReadings(210, 40),
  },
];

export const alarms: Alarm[] = [
  {
    id: "alarm_1",
    assetId: "asset_ahu-07",
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    assetLabel: "AHU AHU-07",
    message: "Supply air temperature deviation > 6°C from setpoint",
    severity: "critical",
    raisedAt: "2026-07-19T07:52:00+01:00",
    status: "converted",
    source: "BACnet/IP",
  },
  {
    id: "alarm_2",
    assetId: "asset_el-22",
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    assetLabel: "Emergency Lighting EL-22",
    message: "Self-test failure reported by panel",
    severity: "critical",
    raisedAt: "2026-07-15T14:50:00+01:00",
    status: "converted",
    source: "MQTT",
  },
  {
    id: "alarm_3",
    assetId: "asset_lift-01",
    propertyId: "prop_kings-cross-office",
    propertyName: "Office - King's Cross",
    assetLabel: "Lift LIFT-01",
    message: "Vibration sensor trending above baseline",
    severity: "warning",
    raisedAt: "2026-07-19T08:05:00+01:00",
    status: "active",
    source: "Vendor API",
  },
  {
    id: "alarm_4",
    assetId: "asset_ahu-02",
    propertyId: "prop_coal-drops-4",
    propertyName: "Coal Drops Yard - Unit 4",
    assetLabel: "AHU AHU-02",
    message: "Filter differential pressure approaching threshold",
    severity: "info",
    raisedAt: "2026-07-18T11:00:00+01:00",
    status: "acknowledged",
    source: "MQTT",
  },
];

export function getTelemetryForAsset(assetId: string): TelemetryPoint[] {
  return telemetryPoints.filter((t) => t.assetId === assetId);
}

export function getAlarmsForProperty(propertyId: string): Alarm[] {
  return alarms.filter((a) => a.propertyId === propertyId);
}

// Section 5.11 — Notifications and communications.

export const notifications: NotificationItem[] = [
  {
    id: "notif_1",
    type: "work_order.created",
    title: "New job: SA-1046",
    body: "Ravi Chandra raised \"Unusual noise / vibration\" at Office - King's Cross.",
    timestamp: "2026-07-19T08:20:00+01:00",
    read: false,
    href: "/jobs/wo_1046",
  },
  {
    id: "notif_2",
    type: "bms.alarm_received",
    title: "Critical alarm: AHU AHU-07",
    body: "Supply air temperature deviation triggered a converted work order SA-1044.",
    timestamp: "2026-07-19T07:52:00+01:00",
    read: false,
    href: "/jobs/wo_1044",
  },
  {
    id: "notif_3",
    type: "ppm.overdue",
    title: "PPM overdue: Water hygiene TMV service",
    body: "Retail Unit - Camden — Sink SK-003 service is now overdue.",
    timestamp: "2026-07-19T06:00:00+01:00",
    read: false,
    href: "/compliance",
  },
  {
    id: "notif_4",
    type: "work_order.status_changed",
    title: "SA-1045 awaiting parts",
    body: "Sentinel Fire & Security moved Emergency Lighting EL-22 to Awaiting parts.",
    timestamp: "2026-07-16T09:05:00+01:00",
    read: true,
    href: "/jobs/wo_1045",
  },
  {
    id: "notif_5",
    type: "document.expiring",
    title: "Document review due",
    body: "Electrical Isolation Schedule - Roof Plant is unverified and due for review.",
    timestamp: "2026-07-14T09:00:00+01:00",
    read: true,
    href: "/documents",
  },
  {
    id: "notif_6",
    type: "visit.completed",
    title: "SA-1039 closed",
    body: "S&A Engineer completed and closed the communal door entry fault.",
    timestamp: "2026-07-05T13:30:00+01:00",
    read: true,
    href: "/jobs/wo_1039",
  },
];

export const notificationPreferences: NotificationPreference[] = [
  { eventType: "work_order.created", label: "New job raised", email: true, sms: false, teams: true },
  { eventType: "work_order.status_changed", label: "Job status changed", email: true, sms: false, teams: false },
  { eventType: "visit.completed", label: "Visit completed", email: true, sms: false, teams: false },
  { eventType: "document.expiring", label: "Document expiring / unverified", email: true, sms: false, teams: false },
  { eventType: "ppm.overdue", label: "PPM overdue", email: true, sms: true, teams: true },
  { eventType: "bms.alarm_received", label: "BMS alarm received", email: true, sms: true, teams: true },
];

// Section 5.9 — Contractor and engineer workspace.

export const contractorCompanies: ContractorCompany[] = [
  {
    id: "contractor_metro",
    name: "Metro Plumbing Services",
    trades: ["Plumbing", "Water hygiene"],
    serviceAreas: ["Central London", "East London"],
    insuranceExpiry: "2027-02-01",
    competenceDocuments: 6,
    approved: true,
    responseRate: 96,
    firstTimeFixRate: 88,
  },
  {
    id: "contractor_climate",
    name: "Climate Care Ltd",
    trades: ["HVAC"],
    serviceAreas: ["Central London", "South East London"],
    insuranceExpiry: "2026-11-15",
    competenceDocuments: 8,
    approved: true,
    responseRate: 91,
    firstTimeFixRate: 79,
  },
  {
    id: "contractor_sentinel",
    name: "Sentinel Fire & Security",
    trades: ["Fire", "Electrical", "Life safety"],
    serviceAreas: ["Greater London"],
    insuranceExpiry: "2027-05-20",
    competenceDocuments: 11,
    approved: true,
    responseRate: 98,
    firstTimeFixRate: 92,
  },
];

export const quotations: Quotation[] = [
  {
    id: "quote_1",
    workOrderId: "wo_1045",
    workOrderReference: "SA-1045",
    contractor: "Sentinel Fire & Security",
    amount: 245,
    version: 2,
    status: "approved",
    submittedAt: "2026-07-16T10:00:00+01:00",
    notes: "Replacement emergency battery pack and callout labour.",
  },
  {
    id: "quote_2",
    workOrderId: "wo_1044",
    workOrderReference: "SA-1044",
    contractor: "Climate Care Ltd",
    amount: 890,
    version: 1,
    status: "submitted",
    submittedAt: "2026-07-19T10:30:00+01:00",
    notes: "Compressor diagnostics and part replacement, subject to approval.",
  },
  {
    id: "quote_3",
    workOrderId: "wo_1043",
    workOrderReference: "SA-1043",
    contractor: "Climate Care Ltd",
    amount: 0,
    version: 1,
    status: "requested",
    notes: "Awaiting site diagnosis before quotation can be prepared.",
  },
  {
    id: "quote_4",
    workOrderId: "wo_1048",
    workOrderReference: "SA-1048",
    contractor: "Metro Plumbing Services",
    amount: 0,
    version: 1,
    status: "requested",
    notes: "Blockage may require drain camera survey — quote pending site visit.",
  },
  {
    id: "quote_5",
    workOrderId: "wo_1042",
    workOrderReference: "SA-1042",
    contractor: "Metro Plumbing Services",
    amount: 165,
    version: 1,
    status: "approved",
    submittedAt: "2026-07-17T15:00:00+01:00",
    notes: "Thermostatic mixing valve replacement and callout.",
  },
];

export function getQuotationsForContractor(contractorName: string): Quotation[] {
  return quotations.filter((q) => q.contractor === contractorName);
}

export function getWorkOrdersForContractor(contractorName: string): WorkOrder[] {
  return workOrders.filter((w) => w.assignedTo === contractorName);
}
